MODEL: "strider"
STRIDER:
  VERSION: 1
  USE_FPN: True
  STEM_CONFIG: "BASE"
  STEM_CHANNELS: [64]
  BODY_CHANNELS: [[64, 64, 256], [256, 64, 256], [256, 64, 256], [256, 128, 512], [512, 128, 512], [512, 128, 512], [512, 128, 512],[512, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 512, 2048], [2048, 512, 2048], [2048, 512, 2048]]
  BODY_CONFIG: [[1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]
  STRIDE_OPTION: 0
  OUTPUT_SIZES: [1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1]
  RETURN_FEATURES: [False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, True]
  DILATIONS: [3, 2, 1]
  OUT_CHANNELS: 2048
  FPN_OUT_CHANNELS: 256
  FULL_RESIDUAL: False
  WEIGHTED_FUSION: False
