MODEL: "strider"
STRIDER:
  VERSION: 2
  USE_FPN: True
  STEM_CONFIG: "BASE"
  STEM_CHANNELS: [64]
  BODY_CHANNELS: [[64, 64, 256], [256, 64, 256], [256, 64, 256], [256, 128, 512], [512, 128, 512], [512, 128, 512], [512, 128, 512],[512, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 256, 1024], [1024, 512, 2048], [2048, 512, 2048], [2048, 512, 2048]]
  BODY_CONFIG: [[1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]
  BRANCH_CONFIG: [[False, [2, 2], [3, 3]], [False, [1, 1], [2, 2]], [True, [2, 2], [1, 1]], [False, [1, 2], [1, 2]], [False, [2, 1], [2, 1]]]
  OUTPUT_INDEXES: [1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1]
  RETURN_FEATURES: [False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, True]
  OUT_CHANNELS: 2048
  FPN_OUT_CHANNELS: 256
  FULL_RESIDUAL: False
  LR_RESIDUAL: [2, 4, 8]
  SB_ADAPTIVE_FUSION: False
  LR_ADAPTIVE_FUSION: False
  FPN_ADAPTIVE_FUSION: False
